version: "3.9"

services:
    postgres:
        image: postgres:13.3
        volumes:
            - databasevolume:/var/lib/postgresql/data:Z
        env_file:
            - ./.envs/.local/.postgres

volumes:
    logvolume01: {}
    databasevolume: {}
