# Generated by Django 3.2.3 on 2021-05-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_account_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
