# Generated by Django 3.2.3 on 2021-05-30 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.ManyToManyField(to='finance.Money'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.money'),
        ),
    ]
