# Generated by Django 3.2.3 on 2021-05-30 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20210530_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_from_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_from', to='finance.money'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_to_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_to', to='finance.money'),
        ),
    ]
