# Generated by Django 3.2.3 on 2021-05-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.ManyToManyField(blank=True, null=True, to='finance.Money'),
        ),
    ]
