# Generated by Django 3.2.3 on 2021-05-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20210530_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
