# Generated by Django 3.2.3 on 2021-05-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_account_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
