# Generated by Django 3.2.3 on 2021-05-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_account_is_mine'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
