# Generated by Django 3.2.3 on 2021-05-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_account_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(default='', max_length=20),
        ),
    ]
